apiVersion: v1
kind: Service
metadata:
  name: flask-app #was node-app flask-app
  labels:
    app: web
  namespace: default
spec:
  type: LoadBalancer
  ports:
          #  - port: 443
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: web
